// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "middleman-capstone/domain"

	mock "github.com/stretchr/testify/mock"
)

// OrderData is an autogenerated mock type for the OrderData type
type OrderData struct {
	mock.Mock
}

// InsertData provides a mock function with given fields: data, id
func (_m *OrderData) InsertData(data []domain.Items, id int) []domain.Items {
	ret := _m.Called(data, id)

	var r0 []domain.Items
	if rf, ok := ret.Get(0).(func([]domain.Items, int) []domain.Items); ok {
		r0 = rf(data, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Items)
		}
	}

	return r0
}

type mockConstructorTestingTNewOrderData interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrderData creates a new instance of OrderData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrderData(t mockConstructorTestingTNewOrderData) *OrderData {
	mock := &OrderData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
