// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "middleman-capstone/domain"

	mock "github.com/stretchr/testify/mock"

	user "middleman-capstone/feature/users"
)

// MockUser is an autogenerated mock type for the UserData type
type MockUser struct {
	mock.Mock
}

// CreateProductData provides a mock function with given fields: newProduct
func (_m *MockUser) CreateProductData(newProduct domain.ProductUser) domain.ProductUser {
	ret := _m.Called(newProduct)

	var r0 domain.ProductUser
	if rf, ok := ret.Get(0).(func(domain.ProductUser) domain.ProductUser); ok {
		r0 = rf(newProduct)
	} else {
		r0 = ret.Get(0).(domain.ProductUser)
	}

	return r0
}

// DeleteData provides a mock function with given fields: userID
func (_m *MockUser) DeleteData(userID int) (int, error) {
	ret := _m.Called(userID)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteProductData provides a mock function with given fields: productid, id
func (_m *MockUser) DeleteProductData(productid int, id int) (int, error) {
	ret := _m.Called(productid, id)

	var r0 int
	if rf, ok := ret.Get(0).(func(int, int) int); ok {
		r0 = rf(productid, id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(productid, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSpecific provides a mock function with given fields: userID
func (_m *MockUser) GetSpecific(userID int) (domain.User, error) {
	ret := _m.Called(userID)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(int) domain.User); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: newUser
func (_m *MockUser) Insert(newUser domain.User) (int, error) {
	ret := _m.Called(newUser)

	var r0 int
	if rf, ok := ret.Get(0).(func(domain.User) int); ok {
		r0 = rf(newUser)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.User) error); ok {
		r1 = rf(newUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoginData provides a mock function with given fields: authData
func (_m *MockUser) LoginData(authData user.LoginModel) (map[string]interface{}, error) {
	ret := _m.Called(authData)

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(user.LoginModel) map[string]interface{}); ok {
		r0 = rf(authData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(user.LoginModel) error); ok {
		r1 = rf(authData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadAllProductData provides a mock function with given fields: id
func (_m *MockUser) ReadAllProductData(id int) []domain.ProductUser {
	ret := _m.Called(id)

	var r0 []domain.ProductUser
	if rf, ok := ret.Get(0).(func(int) []domain.ProductUser); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProductUser)
		}
	}

	return r0
}

// UpdateData provides a mock function with given fields: data, idUser
func (_m *MockUser) UpdateData(data map[string]interface{}, idUser int) (int, error) {
	ret := _m.Called(data, idUser)

	var r0 int
	if rf, ok := ret.Get(0).(func(map[string]interface{}, int) int); ok {
		r0 = rf(data, idUser)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(map[string]interface{}, int) error); ok {
		r1 = rf(data, idUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProductData provides a mock function with given fields: updatedData
func (_m *MockUser) UpdateProductData(updatedData domain.ProductUser) domain.ProductUser {
	ret := _m.Called(updatedData)

	var r0 domain.ProductUser
	if rf, ok := ret.Get(0).(func(domain.ProductUser) domain.ProductUser); ok {
		r0 = rf(updatedData)
	} else {
		r0 = ret.Get(0).(domain.ProductUser)
	}

	return r0
}

type mockConstructorTestingTNewMockUser interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockUser creates a new instance of MockUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockUser(t mockConstructorTestingTNewMockUser) *MockUser {
	mock := &MockUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
